version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-student
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studentdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - student-net

  student-app:
    image: moatezmathlouthi/projetstudents:latest
    container_name: student-management-app
    restart: always
    ports:
      - "8089:8089"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/studentdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - student-net

volumes:
  mysql_data:

networks:
  student-net:
